name: 10 Basics Variables - Practical Example
run-name: ${{ github.actor }} Explaining Variables with Practical Example - Try Number ${{ github.run_number }}

on: 
  workflow_dispatch

jobs:
  open-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate testing failure
        run: exit 1
      
      - name: Open new issue
        if: failure()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MY_SECRET_TEST }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ vars.MY_VAR_TEST }} \
          -d '{"title":"Testing Failure","body":"This issue opened by github actions"}'
